version: "2.1"
services:
  pyload:
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/pyload:/config
      - /mnt/B_DRIVE/downloads/pyload:/downloads
    ports:
      - 8001:8000
      - 7227:7227 #optional
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8085:80/tcp
      - 443:443/tcp
    environment:
      - TZ=America/Los_Angeles
      - WEBPASSWORD=1qaz
    volumes:
      - /mnt/B_DRIVE/configs/pihole:/etc/pihole/
      - /mnt/B_DRIVE/configs/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/heimdall:/config
    ports:
      - 80:80
      - 444:443
    restart: always
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/komga:/config
      - /mnt/B_DRIVE/media/gs:/books
    ports:
      - 8069:8080
    restart: always
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /mnt/B_DRIVE/configs/calibre-web:/config
      - /mnt/B_DRIVE/media/books:/books
    ports:
      - 8084:8083
    restart: always
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
#      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/B_DRIVE/configs/plex:/config
      - /mnt/B_DRIVE/media/transcode:/transcode
      - /mnt/B_DRIVE/media:/media
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: always