version: "2.1"
services:
  homer:
    image: nx211/docker-homer
    container_name: homer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/homer:/config # optional for access to nginx config
      - /mnt/B_DRIVE/configs/homer/config.yml:/homer/config.yml
    ports:
      - 80:80
      - 443:443
    restart: always
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/komga:/config
      - /mnt/B_DRIVE/media/gs:/books
    ports:
      - 8069:8080
    restart: always
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /mnt/B_DRIVE/configs/calibre-web:/config
      - /mnt/B_DRIVE/media/books:/books
    ports:
      - 8084:8083
    restart: always
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
#      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/B_DRIVE/configs/plex:/config
      - /mnt/B_DRIVE/media/transcode:/transcode
      - /mnt/B_DRIVE/media:/media
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: always