version: "2.1"
services:
  pydio-cells:
    image: linuxserver/pydio-cells
    container_name: pydio-cells
    hostname: pydio-cells
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - EXTERNALURL=yourdomain.url
#      - SERVER_IP=0.0.0.0 #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8080:8080
 #     - 33060:33060 #optional
    restart: unless-stopped
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   environment:
  #     - TZ=America/Los_Angeles
  #     - WEBPASSWORD=1qaz
  #     - ServerIP=192.168.1.119
  #   volumes:
  #     - /mnt/B_DRIVE/configs/pihole:/etc/pihole/
  #     - /mnt/B_DRIVE/configs/dnsmasq.d/:/etc/dnsmasq.d/
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #   # Recommended but not required (DHCP needs NET_ADMIN)
  #   #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #   cap_add:
  #     - NET_ADMIN
  #   restart: always
  #   network_mode: host
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/B_DRIVE/configs/komga:/config
      - /mnt/B_DRIVE/media/gs:/books
    ports:
      - 8069:8080
    restart: unless-stopped
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /mnt/B_DRIVE/configs/calibre-web:/config
      - /mnt/B_DRIVE/media/books:/books
    ports:
      - 8084:8083
    restart: unless-stopped