version: "2.1"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/B_DRIVE/configs/portainer:/data
    ports:
      - 8000:8000
      - 9000:9000
    restart: always