version: '2'

services:
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'npm'
      MARIADB_DATABASE: 'npm'
      MARIADB_USERNAME: 'npm'
      MARIADB_PASSWORD: 'npm'
    volumes:
      - /mnt/B_DRIVE/configs/filerun/mysql:/var/lib/mysql
  web:
    image: afian/filerun:arm32v7
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: 'npm'
      FR_DB_USER: 'npm'
      FR_DB_PASS: 'npm'
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "83:80"
    volumes:
      - /mnt/B_DRIVE/configs/filerun/html:/var/www/html
      - /mnt/B_DRIVE:/user-files
